### ISSUE TITLE
Useless flame about the structure of `plugins.json`

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/awesome-plugins#1]
Dear @EugenioPetulla,
a team of three expert kittens reckons an oddity in the format of your choice for the file `plugins.json`.

We reckon in fact that this structure:
```json
[
    {
         "name": "Mood music for Cheshire Cat",
	 "url": "https://github.com/AndreaPesce2002/mood-music-for-Cheshire-Cat"
    },
    {
        "name": "Cheshire Cat Multilingual",
	"url": "https://github.com/team-sviluppo/cc_multilingual"
    }
]
```

Is more suitable as indexes are implicit. So way better than yours, so you will pay for us a dinner in an expensive restaurant to justify explicit indexing.
In attendance of an official reply, we send you a big hug and thank you for your contribution.

Best regards,
@pieroit 
@zAlweNy26 
@nicola-corbellini

**Comment by EugenioPetulla** [comment]
It was just for indexing purposes, because it acts like a DB but... you got it right, ATM it's almost useless... maybe I can reintroduce it in the future when the list will be more populated (maybe a mongoDB will be more suitable).

Thank you for the awesome issue guys 🤣
